baseURL = '/'
languageCode = 'en-us'
title = 'Ravi Rai'
theme = "coder"

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 3

[pagination]
  pagerSize = 10


[params]
  author = "Ravi Rai"
  info = "Integration, Cloud, and AI"
  description = "Notes on APIs, architecture, and systems that survive production"
  keywords = "api, architecture, integration, webmethods, cloud, ai"
  avatarURL = "images/avatar.jpg"
  colorScheme = "auto"
  favicon_32 = "/images/favicon/favicon_32.png"
  favicon_16 = "/images/favicon/favicon_16.png"

[[params.social]]
  name = "GitHub"
  icon = "fa fa-github"
  weight = 1
  url = "https://github.com/r-rai"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin"
  weight = 2
  url = "https://www.linkedin.com/in/ravikumarrai"
[[params.social]]
  name = "Email"
  icon = "fa fa-envelope"
  weight = 3
  url = "mailto:ravi@ravirai.in"

[markup.goldmark.renderer]
  unsafe = true